export const hotelTypes = [
    "Apartment",
    "Hotel",
    "Homestay",
    "Guest house",
    "Villa",
    "Love hotel",
    "Capsule hotel",
    "Holiday home",
    "Resort",
    "Boutique hotel",
    "Hostel",
    "Motel",
    "Farm stay",
    "Cottage",
    "Bungalow",
    "Chalet",
    "Ryokan",
    "Bed and Breakfast",
    "Lodge",
    "Inn",
  ];
  
  export const hotelFacilities = [
    "bathroom",
    "Balcony",
    "Sea view",
    "Air conditioning",
    "Kitchen",
    "Outdoor Pool",
    "TV",
    "WiFi",
    "Parking",
    "Restaurant",
    "Bar",
    "Spa",
    "Fitness center",
    "Pet friendly",
    "24-hour front desk",
    "Room service",
    "Laundry",
    "Airport shuttle",
    "Non-smoking rooms",
    "Family rooms",
    "Breakfast included",
    "Elevator",
    "Garden",
    "Terrace",
    "Business center",
    "Conference room",
    "Sauna",
    "Hot tub",
    "Playground",
    "Bicycle rental",
    "Car rental",
  ];